export const NEW_EXPENSE = 'NEW_EXPENSE';

export const FETCH_EXPENSES_BEGIN   = 'FETCH_EXPENSES_BEGIN';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

export const FETCH_EXPENSES_CREATE   = 'FETCH_EXPENSES_CREATE';