// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    [Migration("20201217080500_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.TestValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestValues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58e46b6f-1379-42a2-9009-f18117b418ec"),
                            Description = "Lorem ipsum dolor1",
                            Title = "Test Value 1"
                        },
                        new
                        {
                            Id = new Guid("2f800fb0-ccb3-4ca7-8bdc-8cfedab27c95"),
                            Description = "Lorem ipsum dolor2",
                            Title = "Test Value 2"
                        },
                        new
                        {
                            Id = new Guid("d81c4744-d4b3-4786-8690-f3bab0499b74"),
                            Description = "Lorem ipsum dolor3",
                            Title = "Test Value 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
